src/AbpCompanyName.AbpProjectName.WebMpa/Models/Layout/LanguageSelectionViewModel.cs
using System.Collections.Generic;
using Abp.Localization;

namespace AbpCompanyName.AbpProjectName.WebMpa.Models.Layout
{
    public class LanguageSelectionViewModel
    {
        public LanguageInfo CurrentLanguage { get; set; }

        public IReadOnlyList<LanguageInfo> Languages { get; set; }
    }
}

src/AbpCompanyName.AbpProjectName.WebMpa/Models/Layout/TopMenuViewModel.cs
using Abp.Application.Navigation;

namespace AbpCompanyName.AbpProjectName.WebMpa.Models.Layout
{
    public class TopMenuViewModel
    {
        public UserMenu MainMenu { get; set; }

        public string ActiveMenuItemName { get; set; }
    }
}

src/AbpCompanyName.AbpProjectName.WebMpa/Controllers/AboutController.cs
using System.Web.Mvc;

namespace AbpCompanyName.AbpProjectName.WebMpa.Controllers
{
    public class AboutController : AbpProjectNameControllerBase
    {
        public ActionResult Index()
        {
            return View();
        }
	}
}

src/AbpCompanyName.AbpProjectName.WebMpa/Controllers/HomeController.cs
using System.Web.Mvc;

namespace AbpCompanyName.AbpProjectName.WebMpa.Controllers
{
    public class HomeController : AbpProjectNameControllerBase
    {
        public ActionResult Index()
        {
            return View();
        }
	}
}

src/AbpCompanyName.AbpProjectName.WebMpa/Controllers/LayoutController.cs
using System.Web.Mvc;
using Abp.Application.Navigation;
using Abp.Localization;
using Abp.Runtime.Session;
using Abp.Threading;
using AbpCompanyName.AbpProjectName.WebMpa.Models.Layout;

namespace AbpCompanyName.AbpProjectName.WebMpa.Controllers
{
    public class LayoutController : AbpProjectNameControllerBase
    {
        private readonly IUserNavigationManager _userNavigationManager;
        private readonly ILanguageManager _languageManager;

        public LayoutController(
            IUserNavigationManager userNavigationManager, 
            ILocalizationManager localizationManager,
            ILanguageManager languageManager)
        {
            _userNavigationManager = userNavigationManager;
            _languageManager = languageManager;
        }

        [ChildActionOnly]
        public PartialViewResult TopMenu(string activeMenu = "")
        {
            var model = new TopMenuViewModel
                        {
                            MainMenu = AsyncHelper.RunSync(() => _userNavigationManager.GetMenuAsync("MainMenu", AbpSession.ToUserIdentifier())),
                            ActiveMenuItemName = activeMenu
                        };

            return PartialView("_TopMenu", model);
        }

        [ChildActionOnly]
        public PartialViewResult LanguageSelection()
        {
            var model = new LanguageSelectionViewModel
                        {
                            CurrentLanguage = _languageManager.CurrentLanguage,
                            Languages = _languageManager.GetLanguages()
                        };

            return PartialView("_LanguageSelection", model);
        }
    }
}

src/AbpCompanyName.AbpProjectName.WebMpa/Views/About/Index.cshtml
@{
    ViewBag.ActiveMenu = "About"; //The menu item will be active for this page.
}
<div>
    <h1><img src="~/images/abp-logo.png" style="padding-right: 10px;" />@string.Format(L("AboutFormat"), "ASP.NET Boilerplate")</h1>
    <p>@Html.Raw(L("About_AspNetBoilerplateDescription"))</p>
    <p>@L("ForMoreInformation"): <a href="http://www.aspnetboilerplate.com"><strong>aspnetboilerplate.com</strong></a>.</p>
</div>

src/AbpCompanyName.AbpProjectName.WebMpa/Views/Home/Index.cshtml
@{
    ViewBag.ActiveMenu = "Home"; //The menu item will be active for this page.
}
<div>
    <h1>@L("WelcomeMessage")!</h1>
    <p class="lead">@L("Home_ThisIsATemplate")</p>
    <div class="row">
        <div class="col-md-4">
            <h3>ASP.NET MVC</h3>
            <p>
                @L("Home_AspNetDescription")
            </p>
            <a class="btn btn-primary btn-sm" href="http://asp.net/mvc">@L("LearnMore")..</a>
        </div>
        <div class="col-md-4">
            <h3>ASP.NET Boilerplate</h3>
            <p>
                @L("Home_AspNetBoilerplateDescription")
            </p>
            <a class="btn btn-primary btn-sm" href="http://aspnetboilerplate.com">@L("LearnMore")..</a>
        </div>
        <div class="col-md-4">
            <h3>@L("Others")</h3>
            <p>
                @L("Home_OtherTools")
            </p>
        </div>
    </div>
</div>

src/AbpCompanyName.AbpProjectName.WebMpa/Views/Layout/_LanguageSelection.cshtml
@model AbpCompanyName.AbpProjectName.WebMpa.Models.Layout.LanguageSelectionViewModel
<li class="dropdown">
    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
        <i class="@Model.CurrentLanguage.Icon"></i>
        <span>@Model.CurrentLanguage.DisplayName</span>
        <b class="caret"></b>
    </a>
    <ul class="dropdown-menu">
        @foreach (var language in Model.Languages)
        {
            if (language.Name != Model.CurrentLanguage.Name)
            {
                <li><a href="@Url.Action("ChangeCulture", "AbpLocalization")?cultureName=@(language.Name)&returnUrl=@(Request.Url)"><i class="@language.Icon"></i> @language.DisplayName</a></li>
            }
        }
    </ul>
</li>

src/AbpCompanyName.AbpProjectName.WebMpa/Views/Layout/_TopMenu.cshtml
@using Abp.Collections.Extensions
@using AbpCompanyName.AbpProjectName.WebMpa.Views
@model AbpCompanyName.AbpProjectName.WebMpa.Models.Layout.TopMenuViewModel
@{
    var calculateMenuUrl = new Func<string, string>((url) =>
    {
        if (string.IsNullOrEmpty(url))
        {
            return ApplicationPath;
        }

        if (UrlChecker.IsRooted(url))
        {
            return url;
        }

        return ApplicationPath + url;
    });
}
@foreach (var menuItem in Model.MainMenu.Items)
{
    <li class="@(Model.ActiveMenuItemName == menuItem.Name ? "active" : "")">
        @if (menuItem.Items.IsNullOrEmpty())
        {
            <a href="@calculateMenuUrl(menuItem.Url)">
                @if (!string.IsNullOrWhiteSpace(menuItem.Icon))
                {
                    <i class="@menuItem.Icon"></i>
                }
                @menuItem.DisplayName
            </a>
        }
        else
        {
            <a href="" data-toggle="dropdown">
                @if (!string.IsNullOrWhiteSpace(menuItem.Icon))
                {
                    <i class="@menuItem.Icon"></i>
                }
                @menuItem.DisplayName
            </a>
            <ul class="dropdown-menu">
                @foreach (var subMenuItem in menuItem.Items)
                {
                    <li>
                        <a href="@calculateMenuUrl(subMenuItem.Url)">
                            @if (!string.IsNullOrWhiteSpace(subMenuItem.Icon))
                            {
                                <i class="@subMenuItem.Icon"></i>
                            }
                            @subMenuItem.DisplayName
                        </a>
                    </li>
                }
            </ul>
        }
    </li>
}

src/AbpCompanyName.AbpProjectName.WebMpa/Views/Shared/_Layout.cshtml
@using System.Threading
@using System.Web.Optimization
@using Abp.Timing
@using Abp.Dependency
@using Abp.Web.Mvc.Alerts
@{
    SetAntiForgeryCookie();
    AlertList alerts = null;
    IocManager.Instance.Using<IAlertManager>(alertManager => alerts = alertManager.Alerts);
}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <link rel="shortcut icon" href="~/favicon.ico">

    <title>AbpProjectName</title>

    @Styles.Render("~/Bundles/vendor/css")
    @Styles.Render("~/Bundles/css")

    <!-- View specific styles -->
    @RenderSection("styles", required: false)

    <script type="text/javascript">
        //This is used to get the application's root path from javascript. It's useful if you're running application in a virtual directory under IIS.
        var abp = abp || {}; abp.appPath = '@ApplicationPath';
    </script>

    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
        <script src="@Url.Content("~/Scripts/others/html5shiv.js")"></script>
        <script src="@Url.Content("~/Scripts/others/respond.min.js")"></script>
    <![endif]-->

    @Scripts.Render("~/Bundles/vendor/js/top")

</head>
<body>
    @Html.Partial("_TopBar")

    <div class="container">
        @if (alerts.Any())
        {
            <div id="AbpPageAlerts">
                @foreach (var alertMessage in alerts)
                {
                    <div class="alert alert-@alertMessage.Type.ToString().ToLower() @(alertMessage.Dismissible ? "alert-dismisable" : "")" role="alert">
                        <h4 class="alert-heading">
                            @alertMessage.Title
                            @if (alertMessage.Dismissible)
                            {
                                <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                            }
                        </h4>
                        <p>@alertMessage.Text</p>
                    </div>
                }
            </div>
        }
        @RenderBody()
    </div>

    @Scripts.Render("~/Bundles/vendor/js/bottom")
    @Scripts.Render("~/Bundles/js")

    <script>
        abp.localization.defaultSourceName = '@LocalizationSourceName';
        moment.locale('@Thread.CurrentThread.CurrentUICulture.Name.ToLower()'); //Localizing momentjs
    </script>

    <!-- Dynamic scripts of ABP system (They are created on runtime and can not be bundled) -->
    <script src="~/api/AbpServiceProxies/GetAll?v=@(Clock.Now.Ticks)"></script>
    <script src="~/AbpScripts/GetScripts?v=@(Clock.Now.Ticks)" type="text/javascript"></script>

    <!-- View specific scripts -->
    @RenderSection("scripts", required: false)
</body>
</html>

src/AbpCompanyName.AbpProjectName.WebMpa/Views/Shared/_TopBar.cshtml
<div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="~/"><i class="fa fa-cubes"></i> AbpProjectName</a>
        </div>
        <div class="collapse navbar-collapse">
            <ul class="nav navbar-nav">
                @Html.Action("TopMenu", "Layout", new { activeMenu = ViewBag.ActiveMenu })
            </ul>
            <ul class="nav navbar-nav navbar-right">
                @Html.Action("LanguageSelection", "Layout")
            </ul>
        </div>
    </div>
</div>